// <auto-generated />
using System;
using Babel.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Babel.Core.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260903224610_TheAuditTrailAndTheUsageMeterSurviveARestart")]
    partial class TheAuditTrailAndTheUsageMeterSurviveARestart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Babel.Core.Persistence.AccessCredentialRow", b =>
                {
                    b.Property<string>("Digest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digest");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("kind");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Digest")
                        .HasName("pk_access_credential");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_access_credential_session");

                    b.ToTable("access_credential", "core", t =>
                        {
                            t.HasCheckConstraint("ck_access_credential_digest_shape", "digest ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_access_credential_generation", "generation >= 1");

                            t.HasCheckConstraint("ck_access_credential_kind", "kind in ('access','refresh')");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.AccessEnrolmentRow", b =>
                {
                    b.Property<string>("Digest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("digest");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Digest")
                        .HasName("pk_access_enrolment");

                    b.ToTable("access_enrolment", "core", t =>
                        {
                            t.HasCheckConstraint("ck_access_enrolment_digest_shape", "digest ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.AccessMembershipRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name_ar");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("CompanyId", "UserId")
                        .HasName("pk_access_membership");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_access_membership_tenant_user");

                    b.ToTable("access_membership", "core", t =>
                        {
                            t.HasCheckConstraint("ck_access_membership_name_not_blank", "length(btrim(display_name_ar)) > 0");

                            t.HasCheckConstraint("ck_access_membership_role", "role in ('reader','contributor','owner')");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.AccessSessionRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_access_session");

                    b.ToTable("access_session", "core", t =>
                        {
                            t.HasCheckConstraint("ck_access_session_generation", "generation >= 1");

                            t.HasCheckConstraint("ck_access_session_reason_closed", "revoked_reason in ('', 'signed_out', 'refresh_replayed')");

                            t.HasCheckConstraint("ck_access_session_reason_matches_state", "(revoked_at is not null) = (length(btrim(revoked_reason)) > 0)");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.AuditEntryRow", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNo"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SequenceNo")
                        .HasName("pk_audit_entry");

                    b.HasIndex("TenantId", "OccurredAt", "SequenceNo")
                        .HasDatabaseName("ix_audit_entry_tenant_occurred");

                    b.ToTable("audit_entry", "core", t =>
                        {
                            t.HasCheckConstraint("ck_audit_entry_action_shape", "action ~ '^[a-z][a-z0-9_.]{0,63}$'");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileCapabilityRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("Capability")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("CompanyId", "DocumentType", "Capability")
                        .HasName("pk_capability_profile_capability");

                    b.ToTable("capability_profile_capability", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileDefaultRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("value");

                    b.HasKey("CompanyId", "DocumentType", "Field")
                        .HasName("pk_capability_profile_default");

                    b.ToTable("capability_profile_default", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileDocumentRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.HasKey("CompanyId", "DocumentType")
                        .HasName("pk_capability_profile_document");

                    b.ToTable("capability_profile_document", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CompanySetupRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("DefaultCostCenter")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_cost_center");

                    b.Property<DateTimeOffset>("FoundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("founded_at");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.HasKey("CompanyId")
                        .HasName("pk_company_setup");

                    b.ToTable("company_setup", "core", t =>
                        {
                            t.HasCheckConstraint("ck_company_setup_default_shape", "default_cost_center ~ '^[a-z0-9._]{1,32}$'");

                            t.HasCheckConstraint("ck_company_setup_name_not_blank", "length(btrim(name_ar)) > 0");

                            t.HasCheckConstraint("ck_company_setup_scale_range", "decimal_places between 0 and 4");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.CoreNameTranslationRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("EntityKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_key");

                    b.Property<string>("LanguageTag")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language_tag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("CompanyId", "EntityKind", "EntityKey", "LanguageTag")
                        .HasName("pk_core_name_translation");

                    b.ToTable("name_translation", "core", t =>
                        {
                            t.HasCheckConstraint("ck_core_name_translation_key_not_blank", "length(btrim(entity_key)) > 0");

                            t.HasCheckConstraint("ck_core_name_translation_kind", "entity_kind in ('company','cost_center')");

                            t.HasCheckConstraint("ck_core_name_translation_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_core_name_translation_not_arabic", "lower(language_tag) <> 'ar' and lower(language_tag) not like 'ar-%'");

                            t.HasCheckConstraint("ck_core_name_translation_tag_shape", "language_tag ~ '^[A-Za-z][A-Za-z0-9]*(-[A-Za-z0-9]+)*$' and length(language_tag) <= 35");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.CostCenterRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("")
                        .HasColumnName("suspension_reason");

                    b.HasKey("CompanyId", "Code")
                        .HasName("pk_cost_center");

                    b.ToTable("cost_center", "core", t =>
                        {
                            t.HasCheckConstraint("ck_cost_center_code_shape", "code ~ '^[a-z0-9._]{1,32}$'");

                            t.HasCheckConstraint("ck_cost_center_name_not_blank", "length(btrim(name_ar)) > 0");

                            t.HasCheckConstraint("ck_cost_center_reason_matches_state", "(state = 'suspended') = (length(btrim(suspension_reason)) > 0)");

                            t.HasCheckConstraint("ck_cost_center_state", "state in ('active','suspended')");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.ModuleUsageRow", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNo"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<int>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SequenceNo")
                        .HasName("pk_module_usage");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_module_usage_tenant_occurred");

                    b.ToTable("module_usage", "core", t =>
                        {
                            t.HasCheckConstraint("ck_module_usage_module", "module >= 1");

                            t.HasCheckConstraint("ck_module_usage_operation_not_blank", "length(btrim(operation)) > 0");

                            t.HasCheckConstraint("ck_module_usage_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.UserActivityRow", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNo"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("activity");

                    b.Property<string>("EntitlementState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entitlement_state");

                    b.Property<int>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("module");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SequenceNo")
                        .HasName("pk_user_activity");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_user_activity_tenant_occurred");

                    b.ToTable("user_activity", "core", t =>
                        {
                            t.HasCheckConstraint("ck_user_activity_activity_not_blank", "length(btrim(activity)) > 0");

                            t.HasCheckConstraint("ck_user_activity_entitlement_state", "entitlement_state in ('not_entitled','read_only','entitled')");

                            t.HasCheckConstraint("ck_user_activity_module", "module >= 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
