// <auto-generated />
using System;
using Babel.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Babel.Core.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileCapabilityRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("Capability")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("CompanyId", "DocumentType", "Capability")
                        .HasName("pk_capability_profile_capability");

                    b.ToTable("capability_profile_capability", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileDefaultRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("value");

                    b.HasKey("CompanyId", "DocumentType", "Field")
                        .HasName("pk_capability_profile_default");

                    b.ToTable("capability_profile_default", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CapabilityProfileDocumentRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.HasKey("CompanyId", "DocumentType")
                        .HasName("pk_capability_profile_document");

                    b.ToTable("capability_profile_document", "core");
                });

            modelBuilder.Entity("Babel.Core.Persistence.CompanySetupRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("DefaultCostCenter")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_cost_center");

                    b.Property<DateTimeOffset>("FoundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("founded_at");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.HasKey("CompanyId")
                        .HasName("pk_company_setup");

                    b.ToTable("company_setup", "core", t =>
                        {
                            t.HasCheckConstraint("ck_company_setup_default_shape", "default_cost_center ~ '^[a-z0-9._]{1,32}$'");

                            t.HasCheckConstraint("ck_company_setup_name_not_blank", "length(btrim(name_ar)) > 0");

                            t.HasCheckConstraint("ck_company_setup_scale_range", "decimal_places between 0 and 4");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.CoreNameTranslationRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("EntityKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_key");

                    b.Property<string>("LanguageTag")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language_tag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("CompanyId", "EntityKind", "EntityKey", "LanguageTag")
                        .HasName("pk_core_name_translation");

                    b.ToTable("name_translation", "core", t =>
                        {
                            t.HasCheckConstraint("ck_core_name_translation_key_not_blank", "length(btrim(entity_key)) > 0");

                            t.HasCheckConstraint("ck_core_name_translation_kind", "entity_kind in ('company','cost_center')");

                            t.HasCheckConstraint("ck_core_name_translation_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_core_name_translation_not_arabic", "lower(language_tag) <> 'ar' and lower(language_tag) not like 'ar-%'");

                            t.HasCheckConstraint("ck_core_name_translation_tag_shape", "language_tag ~ '^[A-Za-z][A-Za-z0-9]*(-[A-Za-z0-9]+)*$' and length(language_tag) <= 35");
                        });
                });

            modelBuilder.Entity("Babel.Core.Persistence.CostCenterRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("")
                        .HasColumnName("suspension_reason");

                    b.HasKey("CompanyId", "Code")
                        .HasName("pk_cost_center");

                    b.ToTable("cost_center", "core", t =>
                        {
                            t.HasCheckConstraint("ck_cost_center_code_shape", "code ~ '^[a-z0-9._]{1,32}$'");

                            t.HasCheckConstraint("ck_cost_center_name_not_blank", "length(btrim(name_ar)) > 0");

                            t.HasCheckConstraint("ck_cost_center_reason_matches_state", "(state = 'suspended') = (length(btrim(suspension_reason)) > 0)");

                            t.HasCheckConstraint("ck_cost_center_state", "state in ('active','suspended')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
