// <auto-generated />
using System;
using Babel.Ledger.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Babel.Ledger.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260824135544_LedgerFoundation")]
    internal partial class LedgerFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Babel.Ledger.Persistence.AccountBalanceRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("BookId")
                        .HasColumnType("text")
                        .HasColumnName("book_id");

                    b.Property<string>("PeriodCode")
                        .HasColumnType("text")
                        .HasColumnName("period_code");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<decimal>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("debit");

                    b.Property<long>("EntryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("entry_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId", "BookId", "PeriodCode", "Code")
                        .HasName("pk_account_balance");

                    b.HasIndex("CompanyId", "Code");

                    b.ToTable("account_balance", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_balance_sign", "debit >= 0 and credit >= 0");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.AccountRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<string>("CaveatAr")
                        .HasColumnType("text")
                        .HasColumnName("caveat_ar");

                    b.Property<string>("CaveatEn")
                        .HasColumnType("text")
                        .HasColumnName("caveat_en");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("any")
                        .HasColumnName("currency_mode");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsContra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_contra");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<bool>("IsProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_protected");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("account_level");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameArSearch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name_ar_search");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NaturalSide")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("natural_side");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text")
                        .HasColumnName("parent_code");

                    b.PrimitiveCollection<string[]>("RequiredDimensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("required_dimensions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("StatementSection")
                        .HasColumnType("text")
                        .HasColumnName("statement_section");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("drafted")
                        .HasColumnName("status");

                    b.Property<string>("SubledgerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("subledger_type");

                    b.HasKey("CompanyId", "Code")
                        .HasName("pk_account");

                    b.HasIndex("CompanyId", "NameArSearch")
                        .HasDatabaseName("ix_account_search");

                    b.HasIndex("CompanyId", "ParentCode")
                        .HasDatabaseName("ix_account_parent");

                    b.ToTable("account", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_currency_mode", "currency_mode in ('any','company_only','fixed')");

                            t.HasCheckConstraint("ck_account_fixed_currency", "currency_mode <> 'fixed' or currency_code is not null");

                            t.HasCheckConstraint("ck_account_level", "account_level between 1 and 4");

                            t.HasCheckConstraint("ck_account_level_matches_code", "(account_level = 1 and length(account_code) = 1) or (account_level = 2 and length(account_code) = 2) or (account_level = 3 and length(account_code) = 3) or (account_level = 4 and length(account_code) >= 4)");

                            t.HasCheckConstraint("ck_account_natural_side", "natural_side in ('debit','credit')");

                            t.HasCheckConstraint("ck_account_parent_matches_code", "(parent_code is null and account_level = 1) or (parent_code is not null and account_code like parent_code || '%' and length(account_code) > length(parent_code))");

                            t.HasCheckConstraint("ck_account_postable_is_leaf", "not is_postable or account_level = 4");

                            t.HasCheckConstraint("ck_account_type", "account_type in ('asset','liability','equity','revenue','expense')");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.ChainLinkRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("BookId")
                        .HasColumnType("text")
                        .HasColumnName("book_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("ChainSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("chain_seq");

                    b.Property<string>("CanonVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canon_version");

                    b.Property<byte[]>("CanonicalBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("canonical_bytes");

                    b.Property<byte[]>("EntryHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("entry_hash");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<byte[]>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("prev_hash");

                    b.HasKey("CompanyId", "BookId", "FiscalYear", "ChainSeq")
                        .HasName("pk_chain_link");

                    b.HasIndex("EntryId")
                        .IsUnique()
                        .HasDatabaseName("uq_chain_link_entry");

                    b.ToTable("chain_link", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_chain_link_hash_length", "octet_length(entry_hash) = 32 and octet_length(prev_hash) = 32");

                            t.HasCheckConstraint("ck_chain_link_seq_positive", "chain_seq >= 1");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.FiscalPeriodRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<int>("PeriodNo")
                        .HasColumnType("integer")
                        .HasColumnName("period_no");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("text")
                        .HasColumnName("closed_by");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_code");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("state");

                    b.HasKey("CompanyId", "FiscalYear", "PeriodNo")
                        .HasName("pk_fiscal_period");

                    b.HasIndex("CompanyId", "PeriodCode")
                        .IsUnique()
                        .HasDatabaseName("uq_fiscal_period_code");

                    b.ToTable("fiscal_period", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_period_range", "ends_on >= starts_on");

                            t.HasCheckConstraint("ck_fiscal_period_state", "state in ('open','closed','permanently_closed')");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.JournalEntryRow", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("ActorSearch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("actor_search");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book_id");

                    b.Property<string>("ClosedPeriodAuthoriser")
                        .HasColumnType("text")
                        .HasColumnName("closed_period_authoriser");

                    b.Property<string>("ClosedPeriodPermission")
                        .HasColumnType("text")
                        .HasColumnName("closed_period_permission");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<long>("EntryNo")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_no");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("event_code");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("memo");

                    b.Property<string>("MemoAr")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("memo_ar");

                    b.Property<string>("MemoArSearch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("memo_ar_search");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_code");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<int>("PostingGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("posting_generation");

                    b.Property<string>("PostingTriggerCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posting_trigger_code");

                    b.Property<string>("ReversalReasonAr")
                        .HasColumnType("text")
                        .HasColumnName("reversal_reason_ar");

                    b.Property<string>("ReversalReasonEn")
                        .HasColumnType("text")
                        .HasColumnName("reversal_reason_en");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<string>("SourceDocId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_doc_id");

                    b.Property<string>("SourceDocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_doc_type");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EntryId")
                        .HasName("pk_journal_entry");

                    b.HasIndex("ReversesEntryId");

                    b.HasIndex("CompanyId", "BookId", "PeriodCode")
                        .HasDatabaseName("ix_journal_entry_period");

                    b.HasIndex("CompanyId", "SourceDocType", "SourceDocId")
                        .HasDatabaseName("ix_journal_entry_source");

                    b.HasIndex("CompanyId", "BookId", "FiscalYear", "EntryNo")
                        .IsUnique()
                        .HasDatabaseName("uq_journal_entry_no");

                    b.HasIndex("CompanyId", "SourceDocType", "SourceDocId", "PostingTriggerCode", "PostingGeneration")
                        .IsUnique()
                        .HasDatabaseName("uq_posting_identity");

                    b.ToTable("journal_entry", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_journal_entry_generation", "posting_generation >= 1");

                            t.HasCheckConstraint("ck_journal_entry_reversal_has_reason", "status <> 'REVERSAL' or (reverses_entry_id is not null and reversal_reason_ar is not null)");

                            t.HasCheckConstraint("ck_journal_entry_status", "status in ('POSTED','REVERSAL')");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.JournalLineRow", b =>
                {
                    b.Property<Guid>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("BoqItemId")
                        .HasColumnType("text")
                        .HasColumnName("boq_item_id");

                    b.Property<string>("BranchId")
                        .HasColumnType("text")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CostCenterId")
                        .HasColumnType("text")
                        .HasColumnName("cost_center_id");

                    b.Property<decimal>("Credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("credit");

                    b.Property<decimal>("CreditCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("credit_company");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal>("Debit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("debit");

                    b.Property<decimal>("DebitCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("debit_company");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionArSearch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description_ar_search");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<decimal>("FxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,8)")
                        .HasDefaultValue(1m)
                        .HasColumnName("fx_rate");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<string>("PropertyId")
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("Qualifier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("*")
                        .HasColumnName("qualifier");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("role_code");

                    b.Property<string>("SubledgerKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("subledger_kind");

                    b.Property<string>("SubledgerPartyId")
                        .HasColumnType("text")
                        .HasColumnName("subledger_party_id");

                    b.Property<string>("UnitId")
                        .HasColumnType("text")
                        .HasColumnName("unit_id");

                    b.Property<string>("WarehouseId")
                        .HasColumnType("text")
                        .HasColumnName("warehouse_id");

                    b.HasKey("LineId")
                        .HasName("pk_journal_line");

                    b.HasIndex("CompanyId", "Code")
                        .HasDatabaseName("ix_journal_line_account");

                    b.HasIndex("CompanyId", "PropertyId")
                        .HasDatabaseName("ix_journal_line_property");

                    b.HasIndex("EntryId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("uq_journal_line_no");

                    b.ToTable("journal_line", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_journal_line_company_side", "debit_company = 0 or credit_company = 0");

                            t.HasCheckConstraint("ck_journal_line_fx_positive", "fx_rate > 0");

                            t.HasCheckConstraint("ck_journal_line_one_side", "debit = 0 or credit = 0");

                            t.HasCheckConstraint("ck_journal_line_sign", "debit >= 0 and credit >= 0 and debit_company >= 0 and credit_company >= 0");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.PostingCounterRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("BookId")
                        .HasColumnType("text")
                        .HasColumnName("book_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<long>("NextChainSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("next_chain_seq");

                    b.Property<long>("NextEntryNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("next_entry_no");

                    b.HasKey("CompanyId", "BookId", "FiscalYear")
                        .HasName("pk_posting_counter");

                    b.ToTable("posting_counter", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_posting_counter_positive", "next_entry_no >= 1 and next_chain_seq >= 1");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.PostingRoleRow", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("ExpectedAccountType")
                        .HasColumnType("text")
                        .HasColumnName("expected_account_type");

                    b.Property<string>("ExpectedSide")
                        .HasColumnType("text")
                        .HasColumnName("expected_side");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NoteAr")
                        .HasColumnType("text")
                        .HasColumnName("note_ar");

                    b.Property<string>("NoteEn")
                        .HasColumnType("text")
                        .HasColumnName("note_en");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("drafted")
                        .HasColumnName("status");

                    b.HasKey("RoleCode")
                        .HasName("pk_posting_role");

                    b.ToTable("posting_role", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_posting_role_side", "expected_side is null or expected_side in ('debit','credit')");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.ProcessEventRow", b =>
                {
                    b.Property<long>("ProcessEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("process_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ProcessEventId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("EventCode")
                        .HasColumnType("text")
                        .HasColumnName("event_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("MessageAr")
                        .HasColumnType("text")
                        .HasColumnName("message_ar");

                    b.Property<string>("MessageEn")
                        .HasColumnType("text")
                        .HasColumnName("message_en");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<string>("SourceDocId")
                        .HasColumnType("text")
                        .HasColumnName("source_doc_id");

                    b.Property<string>("SourceDocType")
                        .HasColumnType("text")
                        .HasColumnName("source_doc_type");

                    b.HasKey("ProcessEventId")
                        .HasName("pk_process_event");

                    b.HasIndex("CompanyId", "OccurredAt")
                        .HasDatabaseName("ix_process_event_company");

                    b.ToTable("process_event", "ledger");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.PropertyDimensionRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("PropertyId")
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("OwnershipModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_model");

                    b.HasKey("CompanyId", "PropertyId")
                        .HasName("pk_property_dimension");

                    b.ToTable("property_dimension", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_property_ownership_model", "ownership_model in ('own_property','managed_for_others')");
                        });
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.RoleAccountMapRow", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("RoleCode")
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("Qualifier")
                        .HasColumnType("text")
                        .HasColumnName("qualifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("NoteAr")
                        .HasColumnType("text")
                        .HasColumnName("note_ar");

                    b.Property<string>("NoteEn")
                        .HasColumnType("text")
                        .HasColumnName("note_en");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("drafted")
                        .HasColumnName("status");

                    b.HasKey("CompanyId", "RoleCode", "Qualifier")
                        .HasName("pk_role_account_map");

                    b.HasIndex("RoleCode");

                    b.HasIndex("CompanyId", "Code");

                    b.ToTable("role_account_map", "ledger");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.AccountBalanceRow", b =>
                {
                    b.HasOne("Babel.Ledger.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_balance_account");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.ChainLinkRow", b =>
                {
                    b.HasOne("Babel.Ledger.Persistence.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chain_link_entry");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.JournalEntryRow", b =>
                {
                    b.HasOne("Babel.Ledger.Persistence.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .HasConstraintName("fk_journal_entry_reverses");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.JournalLineRow", b =>
                {
                    b.HasOne("Babel.Ledger.Persistence.JournalEntryRow", "Entry")
                        .WithMany("Lines")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_line_entry");

                    b.HasOne("Babel.Ledger.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_line_account");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.RoleAccountMapRow", b =>
                {
                    b.HasOne("Babel.Ledger.Persistence.PostingRoleRow", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_account_map_role");

                    b.HasOne("Babel.Ledger.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_account_map_account");
                });

            modelBuilder.Entity("Babel.Ledger.Persistence.JournalEntryRow", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
