/* ═══════════════════════════════════════════════════════════════════════
   مُولَّد من العقد بـ`scripts/build-showcase-map.mjs` — لا تُحرِّره بيدك.
   المصدر · source: contracts/openapi/v1.json (v1)
   العمليات · operations: 162

   وهذا **ليس** من ملفّات العميل المُولَّد: بوّابة الانحراف `gen:check`
   لا تعرفه ولا يعرفها، وهو يخصّ طبقة العرض وحدها.
   ═══════════════════════════════════════════════════════════════════════ */

/** عمليةٌ في العقد: رمز نجاحها ومخطّط جوابها. */
export interface Operation {
  /** معرّف العملية كما ينشره العقد. */ readonly id: string;
  /** رمز الحالة عند النجاح. */ readonly status: number;
  /** اسم مخطّط الجواب، أو null حين لا يكون JSON. */ readonly schema: string | null;
}

/** كل عمليات العقد، بمفتاح «الفعل ثمّ قالب المسار». */
export const OPERATIONS: Readonly<Record<string, Operation>> = {
  "GET /api/v1/companies/{companyId}/attachments": { id: "listAttachments", status: 200, schema: "AttachmentPage" },
  "GET /api/v1/companies/{companyId}/attachments/{attachmentId}": { id: "readAttachment", status: 200, schema: "Attachment" },
  "GET /api/v1/companies/{companyId}/attachments/{attachmentId}/content": { id: "downloadAttachment", status: 200, schema: null },
  "GET /api/v1/companies/{companyId}/capability-profile": { id: "readCapabilityProfile", status: 200, schema: "CapabilityProfile" },
  "GET /api/v1/companies/{companyId}/change-orders/{changeOrderId}": { id: "readChangeOrder", status: 200, schema: "ChangeOrder" },
  "GET /api/v1/companies/{companyId}/chart-of-accounts": { id: "readChartOfAccounts", status: 200, schema: "PostingChart" },
  "GET /api/v1/companies/{companyId}/client-certificates/{certificateId}": { id: "readClientCertificate", status: 200, schema: "Certificate" },
  "GET /api/v1/companies/{companyId}/customer-receipts/{receiptId}": { id: "readCustomerReceipt", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/customers/{customerId}": { id: "readCustomer", status: 200, schema: "Party" },
  "GET /api/v1/companies/{companyId}/document-shapes/{documentType}": { id: "readDocumentShape", status: 200, schema: "DocumentShape" },
  "GET /api/v1/companies/{companyId}/employee-advances/{advanceId}": { id: "readEmployeeAdvance", status: 200, schema: "HrAdvance" },
  "GET /api/v1/companies/{companyId}/employee-deductions/{deductionId}": { id: "readEmployeeDeduction", status: 200, schema: "HrDeduction" },
  "GET /api/v1/companies/{companyId}/employee-subledger-reconciliation": { id: "reconcileEmployeeSubledger", status: 200, schema: "HrReconciliation" },
  "GET /api/v1/companies/{companyId}/employees/{employeeId}": { id: "readEmployee", status: 200, schema: "HrEmployee" },
  "GET /api/v1/companies/{companyId}/employees/{employeeId}/pay-elements": { id: "listPayElements", status: 200, schema: "HrPayElementList" },
  "GET /api/v1/companies/{companyId}/end-of-service-provisions/{provisionId}": { id: "readEndOfServiceProvision", status: 200, schema: "HrProvision" },
  "GET /api/v1/companies/{companyId}/end-of-service-settlements/{settlementId}": { id: "readEndOfServiceSettlement", status: 200, schema: "HrSettlement" },
  "GET /api/v1/companies/{companyId}/goods-receipts/{receiptId}": { id: "readGoodsReceipt", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/goods-receipts/{receiptId}/lines": { id: "readGoodsReceiptLines", status: 200, schema: "PurchaseDocumentLineList" },
  "GET /api/v1/companies/{companyId}/guarantees/{guaranteeId}": { id: "readGuarantee", status: 200, schema: "Guarantee" },
  "GET /api/v1/companies/{companyId}/inventory-valuation": { id: "readInventoryValuation", status: 200, schema: "InventoryValuation" },
  "GET /api/v1/companies/{companyId}/items": { id: "listItems", status: 200, schema: "ItemList" },
  "GET /api/v1/companies/{companyId}/items/{itemId}": { id: "readItem", status: 200, schema: "Item" },
  "GET /api/v1/companies/{companyId}/journal-entries/{entryId}": { id: "readJournalEntry", status: 200, schema: "JournalEntry" },
  "GET /api/v1/companies/{companyId}/lease-contracts/{leaseId}": { id: "readLeaseContract", status: 200, schema: "Lease" },
  "GET /api/v1/companies/{companyId}/lease-contracts/{leaseId}/schedule": { id: "readLeaseSchedule", status: 200, schema: "LeaseSchedule" },
  "GET /api/v1/companies/{companyId}/ledger-chain/verification": { id: "verifyLedgerChain", status: 200, schema: "ChainVerification" },
  "GET /api/v1/companies/{companyId}/lessees/{lesseeId}": { id: "readLessee", status: 200, schema: "RealEstateParty" },
  "GET /api/v1/companies/{companyId}/memberships": { id: "readMemberships", status: 200, schema: "MembershipList" },
  "GET /api/v1/companies/{companyId}/pay-components": { id: "listPayComponents", status: 200, schema: "HrPayComponentList" },
  "GET /api/v1/companies/{companyId}/payables-aging": { id: "readPayablesAging", status: 200, schema: "AgingReport" },
  "GET /api/v1/companies/{companyId}/payroll-payments/{paymentId}": { id: "readPayrollPayment", status: 200, schema: "HrPayrollPayment" },
  "GET /api/v1/companies/{companyId}/payroll-runs/{runId}": { id: "readPayrollRun", status: 200, schema: "HrPayrollRun" },
  "GET /api/v1/companies/{companyId}/payroll-runs/{runId}/payslips": { id: "listPayslips", status: 200, schema: "HrPayslipList" },
  "GET /api/v1/companies/{companyId}/payroll-settings": { id: "listPayrollSettings", status: 200, schema: "HrPayrollSettingsList" },
  "GET /api/v1/companies/{companyId}/payslips/{payslipId}": { id: "readPayslip", status: 200, schema: "HrPayslip" },
  "GET /api/v1/companies/{companyId}/project-contracts/{contractId}": { id: "readProjectContract", status: 200, schema: "ProjectContract" },
  "GET /api/v1/companies/{companyId}/project-contracts/{contractId}/boq-items": { id: "readBoqItems", status: 200, schema: "BoqItemList" },
  "GET /api/v1/companies/{companyId}/project-contracts/{contractId}/change-orders": { id: "readContractChangeOrders", status: 200, schema: "ChangeOrderList" },
  "GET /api/v1/companies/{companyId}/project-contracts/{contractId}/client-certificates": { id: "readContractClientCertificates", status: 200, schema: "CertificateList" },
  "GET /api/v1/companies/{companyId}/project-contracts/{contractId}/position": { id: "readContractPosition", status: 200, schema: "ContractPosition" },
  "GET /api/v1/companies/{companyId}/projects": { id: "listProjects", status: 200, schema: "ProjectList" },
  "GET /api/v1/companies/{companyId}/projects/{projectId}": { id: "readProject", status: 200, schema: "Project" },
  "GET /api/v1/companies/{companyId}/properties/{propertyId}": { id: "readProperty", status: 200, schema: "Property" },
  "GET /api/v1/companies/{companyId}/property-owners/{ownerId}": { id: "readPropertyOwner", status: 200, schema: "RealEstateParty" },
  "GET /api/v1/companies/{companyId}/purchase-orders/{orderId}": { id: "readPurchaseOrder", status: 200, schema: "PurchaseOrder" },
  "GET /api/v1/companies/{companyId}/purchase-returns/{returnId}": { id: "readPurchaseReturn", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/receivables-aging": { id: "readReceivablesAging", status: 200, schema: "AgingReport" },
  "GET /api/v1/companies/{companyId}/rent-invoices/{invoiceId}": { id: "readRentInvoice", status: 200, schema: "RentInvoice" },
  "GET /api/v1/companies/{companyId}/retention-collections/{collectionId}": { id: "readRetentionCollection", status: 200, schema: "ProjectsDocument" },
  "GET /api/v1/companies/{companyId}/retention-register": { id: "readRetentionRegister", status: 200, schema: "RetentionRegister" },
  "GET /api/v1/companies/{companyId}/retention-releases/{releaseId}": { id: "readRetentionRelease", status: 200, schema: "ProjectsDocument" },
  "GET /api/v1/companies/{companyId}/sales-invoices/{invoiceId}": { id: "readSalesInvoice", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/setup": { id: "readCompanySetup", status: 200, schema: "CompanySetup" },
  "GET /api/v1/companies/{companyId}/social-insurance-payments/{paymentId}": { id: "readSocialInsurancePayment", status: 200, schema: "HrSocialInsurancePayment" },
  "GET /api/v1/companies/{companyId}/stock-balances": { id: "readStockBalances", status: 200, schema: "StockBalanceList" },
  "GET /api/v1/companies/{companyId}/stock-movements": { id: "listStockMovements", status: 200, schema: "StockMovementList" },
  "GET /api/v1/companies/{companyId}/subcontractor-advances/{advanceId}": { id: "readSubcontractorAdvance", status: 200, schema: "ProjectsDocument" },
  "GET /api/v1/companies/{companyId}/subcontractor-certificates/{certificateId}": { id: "readSubcontractorCertificate", status: 200, schema: "Certificate" },
  "GET /api/v1/companies/{companyId}/subcontractor-statement": { id: "readSubcontractorStatement", status: 200, schema: "SubcontractorStatement" },
  "GET /api/v1/companies/{companyId}/subcontractors/{subcontractorId}": { id: "readSubcontractor", status: 200, schema: "Subcontractor" },
  "GET /api/v1/companies/{companyId}/subcontracts/{subcontractId}": { id: "readSubcontract", status: 200, schema: "Subcontract" },
  "GET /api/v1/companies/{companyId}/subcontracts/{subcontractId}/lines": { id: "readSubcontractLines", status: 200, schema: "SubcontractLineList" },
  "GET /api/v1/companies/{companyId}/supplier-bills/{billId}": { id: "readSupplierBill", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/supplier-payments/{paymentId}": { id: "readSupplierPayment", status: 200, schema: "CommercialDocument" },
  "GET /api/v1/companies/{companyId}/suppliers/{supplierId}": { id: "readSupplier", status: 200, schema: "Party" },
  "GET /api/v1/companies/{companyId}/tenant-arrears-aging": { id: "readTenantArrearsAging", status: 200, schema: "TenantArrears" },
  "GET /api/v1/companies/{companyId}/tenant-receipts/{receiptId}": { id: "readTenantReceipt", status: 200, schema: "TenantReceipt" },
  "GET /api/v1/companies/{companyId}/trial-balance": { id: "readTrialBalance", status: 200, schema: "TrialBalance" },
  "GET /api/v1/companies/{companyId}/units/{unitId}": { id: "readUnit", status: 200, schema: "Unit" },
  "GET /api/v1/session": { id: "readSession", status: 200, schema: "Session" },
  "GET /api/v1/tenants/{tenantId}/subscription": { id: "readSubscription", status: 200, schema: "Subscription" },
  "GET /docs": { id: "readDocsPage", status: 200, schema: null },
  "GET /health": { id: "health", status: 200, schema: "HealthResponse" },
  "GET /openapi/v1.json": { id: "readPublishedContract", status: 200, schema: null },
  "POST /api/v1/access/sessions": { id: "openSession", status: 201, schema: "AccessSession" },
  "POST /api/v1/access/sessions/renewal": { id: "renewSession", status: 201, schema: "AccessSession" },
  "POST /api/v1/access/sessions/revocation": { id: "revokeSession", status: 201, schema: "SessionRevocation" },
  "POST /api/v1/companies/{companyId}/attachments": { id: "depositAttachment", status: 201, schema: "Attachment" },
  "POST /api/v1/companies/{companyId}/attachments/{attachmentId}/download-tickets": { id: "issueAttachmentDownloadTicket", status: 201, schema: "AttachmentTicket" },
  "POST /api/v1/companies/{companyId}/attachments/{attachmentId}/revisions": { id: "reviseAttachment", status: 201, schema: "Attachment" },
  "POST /api/v1/companies/{companyId}/attachments/{attachmentId}/withdrawal": { id: "withdrawAttachment", status: 201, schema: "Attachment" },
  "POST /api/v1/companies/{companyId}/change-orders": { id: "addChangeOrder", status: 201, schema: "ChangeOrder" },
  "POST /api/v1/companies/{companyId}/client-certificates": { id: "draftClientCertificate", status: 201, schema: "Certificate" },
  "POST /api/v1/companies/{companyId}/client-certificates/{certificateId}/posting": { id: "postClientCertificate", status: 201, schema: "Certificate" },
  "POST /api/v1/companies/{companyId}/cost-centers": { id: "addCostCenter", status: 201, schema: "CompanySetup" },
  "POST /api/v1/companies/{companyId}/cost-centers/{costCenterCode}/suspension": { id: "suspendCostCenter", status: 201, schema: "CompanySetup" },
  "POST /api/v1/companies/{companyId}/credit-notes": { id: "draftCreditNote", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/credit-notes/{creditNoteId}/posting": { id: "postCreditNote", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/customer-receipts": { id: "draftCustomerReceipt", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/customer-receipts/{receiptId}/posting": { id: "postCustomerReceipt", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/customers": { id: "addCustomer", status: 201, schema: "Party" },
  "POST /api/v1/companies/{companyId}/document-shapes/{documentType}/admissions": { id: "admitDocument", status: 200, schema: "DocumentAdmission" },
  "POST /api/v1/companies/{companyId}/employee-advances": { id: "draftEmployeeAdvance", status: 201, schema: "HrAdvance" },
  "POST /api/v1/companies/{companyId}/employee-deductions": { id: "recordEmployeeDeduction", status: 201, schema: "HrDeduction" },
  "POST /api/v1/companies/{companyId}/employees": { id: "registerEmployee", status: 201, schema: "HrEmployee" },
  "POST /api/v1/companies/{companyId}/employees/{employeeId}/pay-elements": { id: "addPayElement", status: 201, schema: "HrPayElement" },
  "POST /api/v1/companies/{companyId}/employees/{employeeId}/termination": { id: "terminateEmployee", status: 201, schema: "HrEmployee" },
  "POST /api/v1/companies/{companyId}/end-of-service-provisions": { id: "draftEndOfServiceProvision", status: 201, schema: "HrProvision" },
  "POST /api/v1/companies/{companyId}/end-of-service-provisions/{provisionId}/posting": { id: "postEndOfServiceProvision", status: 200, schema: "HrProvision" },
  "POST /api/v1/companies/{companyId}/end-of-service-settlements": { id: "draftEndOfServiceSettlement", status: 201, schema: "HrSettlement" },
  "POST /api/v1/companies/{companyId}/end-of-service-settlements/{settlementId}/posting": { id: "postEndOfServiceSettlement", status: 200, schema: "HrSettlement" },
  "POST /api/v1/companies/{companyId}/goods-receipts": { id: "draftGoodsReceipt", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/goods-receipts/{receiptId}/posting": { id: "postGoodsReceipt", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/guarantees": { id: "addGuarantee", status: 201, schema: "Guarantee" },
  "POST /api/v1/companies/{companyId}/items": { id: "addItem", status: 201, schema: "Item" },
  "POST /api/v1/companies/{companyId}/journal-entries": { id: "postJournalEntry", status: 200, schema: "PostingReceipt" },
  "POST /api/v1/companies/{companyId}/journal-entries/{entryId}/reversal": { id: "reverseJournalEntry", status: 201, schema: "PostingReceipt" },
  "POST /api/v1/companies/{companyId}/lease-contracts": { id: "draftLeaseContract", status: 201, schema: "Lease" },
  "POST /api/v1/companies/{companyId}/lease-contracts/{leaseId}/activation": { id: "activateLeaseContract", status: 201, schema: "Lease" },
  "POST /api/v1/companies/{companyId}/lessees": { id: "createLessee", status: 201, schema: "RealEstateParty" },
  "POST /api/v1/companies/{companyId}/memberships": { id: "grantMembership", status: 201, schema: "GrantedMembership" },
  "POST /api/v1/companies/{companyId}/memberships/{membershipId}/revocation": { id: "revokeMembership", status: 201, schema: "MembershipRevocation" },
  "POST /api/v1/companies/{companyId}/memberships/{membershipId}/role-changes": { id: "changeMembershipRole", status: 201, schema: "MembershipRoleChange" },
  "POST /api/v1/companies/{companyId}/pay-components": { id: "addPayComponent", status: 201, schema: "HrPayComponent" },
  "POST /api/v1/companies/{companyId}/payroll-payments": { id: "draftPayrollPayment", status: 201, schema: "HrPayrollPayment" },
  "POST /api/v1/companies/{companyId}/payroll-payments/{paymentId}/posting": { id: "postPayrollPayment", status: 200, schema: "HrPayrollPayment" },
  "POST /api/v1/companies/{companyId}/payroll-runs": { id: "draftPayrollRun", status: 201, schema: "HrPayrollRun" },
  "POST /api/v1/companies/{companyId}/payroll-runs/{runId}/posting": { id: "postPayrollRun", status: 200, schema: "HrPayslipList" },
  "POST /api/v1/companies/{companyId}/payroll-settings": { id: "depositPayrollSettings", status: 201, schema: "HrPayrollSettings" },
  "POST /api/v1/companies/{companyId}/project-contracts": { id: "addProjectContract", status: 201, schema: "ProjectContract" },
  "POST /api/v1/companies/{companyId}/projects": { id: "addProject", status: 201, schema: "Project" },
  "POST /api/v1/companies/{companyId}/properties": { id: "createProperty", status: 201, schema: "Property" },
  "POST /api/v1/companies/{companyId}/properties/{propertyId}/units": { id: "createUnit", status: 201, schema: "Unit" },
  "POST /api/v1/companies/{companyId}/property-owners": { id: "createPropertyOwner", status: 201, schema: "RealEstateParty" },
  "POST /api/v1/companies/{companyId}/purchase-orders": { id: "createPurchaseOrder", status: 201, schema: "PurchaseOrder" },
  "POST /api/v1/companies/{companyId}/purchase-returns": { id: "draftPurchaseReturn", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/purchase-returns/{returnId}/posting": { id: "postPurchaseReturn", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/rent-invoices": { id: "draftRentInvoice", status: 201, schema: "RentInvoice" },
  "POST /api/v1/companies/{companyId}/rent-invoices/{invoiceId}/posting": { id: "postRentInvoice", status: 200, schema: "RentInvoice" },
  "POST /api/v1/companies/{companyId}/retention-collections": { id: "draftRetentionCollection", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/retention-collections/{collectionId}/posting": { id: "postRetentionCollection", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/retention-releases": { id: "draftRetentionRelease", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/retention-releases/{releaseId}/posting": { id: "postRetentionRelease", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/sales-invoices": { id: "draftSalesInvoice", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/sales-invoices/{invoiceId}/posting": { id: "postSalesInvoice", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/social-insurance-payments": { id: "draftSocialInsurancePayment", status: 201, schema: "HrSocialInsurancePayment" },
  "POST /api/v1/companies/{companyId}/social-insurance-payments/{paymentId}/posting": { id: "postSocialInsurancePayment", status: 200, schema: "HrSocialInsurancePayment" },
  "POST /api/v1/companies/{companyId}/stock-bills": { id: "draftStockBill", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/stock-movements": { id: "draftStockMovement", status: 201, schema: "StockMovement" },
  "POST /api/v1/companies/{companyId}/stock-movements/{movementId}/posting": { id: "postStockMovement", status: 201, schema: "StockMovement" },
  "POST /api/v1/companies/{companyId}/subcontractor-advances": { id: "draftSubcontractorAdvance", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/subcontractor-advances/{advanceId}/posting": { id: "postSubcontractorAdvance", status: 201, schema: "ProjectsDocument" },
  "POST /api/v1/companies/{companyId}/subcontractor-certificates": { id: "draftSubcontractorCertificate", status: 201, schema: "Certificate" },
  "POST /api/v1/companies/{companyId}/subcontractor-certificates/{certificateId}/posting": { id: "postSubcontractorCertificate", status: 201, schema: "Certificate" },
  "POST /api/v1/companies/{companyId}/subcontractors": { id: "addSubcontractor", status: 201, schema: "Subcontractor" },
  "POST /api/v1/companies/{companyId}/subcontracts": { id: "addSubcontract", status: 201, schema: "Subcontract" },
  "POST /api/v1/companies/{companyId}/supplier-bills": { id: "draftExpenseBill", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/supplier-bills/{billId}/posting": { id: "postSupplierBill", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/supplier-payments": { id: "draftSupplierPayment", status: 201, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/supplier-payments/{paymentId}/posting": { id: "postSupplierPayment", status: 200, schema: "CommercialDocument" },
  "POST /api/v1/companies/{companyId}/suppliers": { id: "addSupplier", status: 201, schema: "Party" },
  "POST /api/v1/companies/{companyId}/tenant-receipts": { id: "draftTenantReceipt", status: 201, schema: "TenantReceipt" },
  "POST /api/v1/companies/{companyId}/tenant-receipts/{receiptId}/allocation": { id: "allocateTenantReceipt", status: 200, schema: "TenantReceipt" },
  "POST /api/v1/companies/{companyId}/tenant-receipts/{receiptId}/posting": { id: "postTenantReceipt", status: 200, schema: "TenantReceipt" },
  "POST /api/v1/tenants": { id: "registerTenant", status: 200, schema: "RegisteredTenant" },
  "POST /api/v1/tenants/{tenantId}/subscription/lapse": { id: "lapseSubscription", status: 201, schema: "Subscription" },
  "POST /api/v1/tenants/{tenantId}/subscription/plan-changes": { id: "changeSubscriptionPlan", status: 201, schema: "Subscription" },
  "POST /api/v1/tenants/{tenantId}/subscription/resumption": { id: "resumeSubscription", status: 201, schema: "Subscription" },
  "PUT /api/v1/companies/{companyId}/capability-profile": { id: "writeCapabilityProfile", status: 200, schema: "CapabilityProfile" },
  "PUT /api/v1/companies/{companyId}/cost-centers/{costCenterCode}": { id: "renameCostCenter", status: 200, schema: "CompanySetup" },
  "PUT /api/v1/companies/{companyId}/setup": { id: "initialiseCompanySetup", status: 201, schema: "CompanySetup" },
};

/**
 * أنواع الحقول غير النصّية في كل مخطّط، كما ينشرها العقد. ما ليس هنا نصٌّ أو
 * مخطّطٌ آخر — و`runtime-schema` المُولَّد يقول أيّهما.
 */
export const PLAIN_TYPES: Readonly<Record<string, Readonly<Record<string, "integer" | "number" | "boolean">>>> = {
  AccessSession: {"generation":"integer","writeReachesNothing":"boolean"},
  Attachment: {"byteLength":"integer","version":"integer"},
  AttachmentPage: {"skip":"integer","take":"integer","total":"integer"},
  BoqItem: {"lineNo":"integer"},
  BoqItemList: {"itemCount":"integer"},
  CapabilitySwitch: {"enabled":"boolean"},
  Certificate: {"alreadyPosted":"boolean","sequenceNo":"integer"},
  CertificateLine: {"lineNo":"integer"},
  CertificateList: {"certificateCount":"integer"},
  CertificateRequest: {"sequenceNo":"integer"},
  ChainVerification: {"checked":"integer","ok":"boolean"},
  ChangeOrderList: {"changeOrderCount":"integer"},
  CommercialDocument: {"alreadyPosted":"boolean"},
  CompanySetup: {"decimalPlaces":"integer"},
  ContractPosition: {"postedCertificateCount":"integer"},
  CostCenter: {"isDefault":"boolean"},
  CustomerRequest: {"paymentTermsDays":"integer"},
  DocumentAdmission: {"admitted":"boolean"},
  HrInstalment: {"lineNo":"integer"},
  HrPayComponent: {"entersContributoryWage":"boolean","entersEndOfServiceBase":"boolean"},
  HrPayComponentList: {"itemCount":"integer"},
  HrPayComponentRequest: {"entersContributoryWage":"boolean","entersEndOfServiceBase":"boolean"},
  HrPayElementList: {"itemCount":"integer"},
  HrPayrollPayment: {"alreadyPosted":"boolean"},
  HrPayrollPaymentLine: {"lineNo":"integer"},
  HrPayrollRun: {"payslipCount":"integer"},
  HrPayrollSettingsList: {"itemCount":"integer"},
  HrPayslip: {"alreadyPosted":"boolean"},
  HrPayslipComponent: {"entersContributoryWage":"boolean","lineNo":"integer"},
  HrPayslipList: {"itemCount":"integer"},
  HrProvision: {"alreadyPosted":"boolean"},
  HrReconciliation: {"isReconciled":"boolean","matchedDocuments":"integer"},
  HrSettlement: {"alreadyPosted":"boolean"},
  HrSocialInsurancePayment: {"alreadyPosted":"boolean"},
  InitialiseCompanySetupRequest: {"decimalPlaces":"integer"},
  InventoryValuation: {"isReconciled":"boolean"},
  IssueAttachmentTicketRequest: {"lifetimeSeconds":"integer"},
  ItemList: {"itemCount":"integer"},
  JournalLine: {"lineNo":"integer"},
  LeaseScheduleLine: {"isInvoiced":"boolean","seq":"integer"},
  MembershipList: {"memberCount":"integer"},
  Party: {"paymentTermsDays":"integer"},
  PostJournalEntryRequest: {"generation":"integer"},
  PostingChart: {"accountCount":"integer","postableCount":"integer"},
  PostingChartEntry: {"active":"boolean","contra":"boolean","level":"integer","postable":"boolean"},
  PostingReceipt: {"alreadyPosted":"boolean","generation":"integer","lineCount":"integer"},
  Problem: {"status":"integer"},
  Project: {"isActive":"boolean"},
  ProjectContract: {"guaranteeMonths":"integer"},
  ProjectContractRequest: {"guaranteeMonths":"integer"},
  ProjectList: {"projectCount":"integer"},
  ProjectsDocument: {"alreadyPosted":"boolean"},
  PurchaseDocumentLine: {"lineNo":"integer"},
  PurchaseDocumentLineList: {"lineCount":"integer"},
  PurchaseLine: {"taxRecoverable":"boolean"},
  PurchaseOrderLine: {"lineNo":"integer"},
  RegisteredTenant: {"alreadyRegistered":"boolean"},
  RentInvoice: {"alreadyPosted":"boolean","exemptionReasonPending":"boolean"},
  Session: {"companyCount":"integer"},
  SessionCompany: {"decimalPlaces":"integer"},
  StockBalance: {"hasCostBasis":"boolean"},
  StockBalanceList: {"balanceCount":"integer"},
  StockMovement: {"alreadyPosted":"boolean"},
  StockMovementList: {"movementCount":"integer"},
  Subcontract: {"guaranteeMonths":"integer"},
  SubcontractLine: {"lineNo":"integer"},
  SubcontractLineList: {"lineCount":"integer"},
  SubcontractRequest: {"guaranteeMonths":"integer"},
  Subcontractor: {"isActive":"boolean"},
  SubcontractorStatement: {"isReconciled":"boolean"},
  Subscription: {"includedUsers":"integer"},
  SubscriptionModule: {"postsJournal":"boolean"},
  SupplierRequest: {"paymentTermsDays":"integer"},
  TenantArrears: {"isReconciled":"boolean"},
  TenantReceipt: {"alreadyPosted":"boolean","isAllocated":"boolean"},
  TrialBalance: {"balanced":"boolean","rowCount":"integer"},
  UnitFactor: {"denominator":"integer","numerator":"integer"},
};
